[package]
name = "codingame"
version = "0.1.0"
authors = ["Tatsuya Katsushima"]
edition = "2018"

[dependencies]
rand = { version = "0.7.2", features = ["small_rng"] }
regex = "1.3.0"

[profile.release]
lto = true
panic = 'abort'
